Vict 2
makskostyshen/totalVictory pull request #13
Opened 2023-10-11 15:57 UTC by Ratchet34702

2023-10-11 17:02 UTC, makskostyshen requested changes
Good jos! One minor fix is needed

2023-10-11 17:02 UTC, makskostyshen commented on src/main/java/com/makskostyshen/web/WebLayerMapper.java
> +
It is better to make a constant EMPTY_FIELD_VALUE with value "..."

2023-10-12 11:52 UTC, Ratchet34702 commented
Worked 2h

2023-10-12 17:11 UTC, makskostyshen approved these changes

2023-10-12 17:12 UTC, merged